// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5S_ix4poamWypCV-34m3ZKFhdZo6aUVs',
    appId: '1:711537426858:web:9fa1284d55ab6f8613ebd3',
    messagingSenderId: '711537426858',
    projectId: 'contacts-7917d',
    authDomain: 'contacts-7917d.firebaseapp.com',
    storageBucket: 'contacts-7917d.appspot.com',
    measurementId: 'G-S0NXL9JRVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYmAeYLYwagrkqyY2BkwQjT4DbTwC4WoE',
    appId: '1:711537426858:android:65a4bf3cf76e4bcb13ebd3',
    messagingSenderId: '711537426858',
    projectId: 'contacts-7917d',
    storageBucket: 'contacts-7917d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUr1vWM2zCLuELIab0TUTMz9whfWndsRk',
    appId: '1:711537426858:ios:4ad34c192a77ccb413ebd3',
    messagingSenderId: '711537426858',
    projectId: 'contacts-7917d',
    storageBucket: 'contacts-7917d.appspot.com',
    iosClientId: '711537426858-tuutgims295aqne6u00krtt8d84a3ap8.apps.googleusercontent.com',
    iosBundleId: 'com.example.contacts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUr1vWM2zCLuELIab0TUTMz9whfWndsRk',
    appId: '1:711537426858:ios:4ad34c192a77ccb413ebd3',
    messagingSenderId: '711537426858',
    projectId: 'contacts-7917d',
    storageBucket: 'contacts-7917d.appspot.com',
    iosClientId: '711537426858-tuutgims295aqne6u00krtt8d84a3ap8.apps.googleusercontent.com',
    iosBundleId: 'com.example.contacts',
  );
}
